---
title: "ESVA: Who are you worried about?"
date: "2024-02-16"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r libs}
library(tidyverse)
library(readxl)
library(sf)
library(ggiraph) # https://www.ardata.fr/ggiraph-book/
library(patchwork)
library(ggspatial) # appears to require installation of "rosm" and "prettymapr" as well
```

```{r data}
# pop data
pop_blkgrp <- read_csv("population_blkgrp.csv")
pop_blkgrp <- pop_blkgrp %>% 
  separate_wider_delim(NAME, delim = "; ", 
                       names = c("block_grp", "tract", "county", "state")) %>% 
  mutate(GEOID = as.character(GEOID))

# names
blkgrp_names <- read_excel("tract_names.xlsx", sheet = "blkgrp2020")
blkgrp_names <- blkgrp_names %>% 
  mutate(localityfips = str_pad(localityfips, width = 3, side = "left", pad = "0"),
         tract = str_pad(tract, width = 6, side = "left", pad = "0"),
         GEOID = paste0("51",localityfips,tract,blkgrp),
         names = str_remove(names, "'"))

# geo
blkgrp_geo <- read_sf("esva_blkgrp_shapefile.geojson")

# join
bg_df <- blkgrp_geo %>% 
  left_join(pop_blkgrp, by = "GEOID") %>% 
  left_join(blkgrp_names, by = "GEOID") %>% 
  mutate(toolinfo = paste0(names, "\n", 
                           "Percent: ", round(percent_lowage_w, 1),
                           "\n", "Number: ", jobs_lowage_w))


## colors
pal <- c("#3aadfc", "#e74b77")
```

```{r map1}
### Jobs paying less than 15K 
gg_map <- ggplot(bg_df) +
  # annotation_map_tile(type = "cartolight") +
  geom_sf_interactive(aes(fill = percent_lowage_w,
                          tooltip = toolinfo, data_id = GEOID), 
                      color = "white") +
  scale_fill_gradient(low = "grey90", high = "darkgreen", 
                      name = "Percent\nof Workers\nin Low-wage\nJobs") +
  theme_void() +
  theme(legend.title = element_text(size = 6),
        legend.text = element_text(size = 5),
        legend.position = c(.8, .4))

# girafe(ggobj = gg_map)

gg_map_tile <- ggplot(bg_df) +
  annotation_map_tile(type = "cartolight") +
  geom_sf_interactive(aes(fill = percent_lowage_w,
                          tooltip = toolinfo, data_id = GEOID), 
                      color = "white", alpha = 1/2) +
  scale_fill_gradient(low = "grey90", high = "darkgreen", 
                      name = "Percent\nof Workers\nin Low-wage\nJobs") +
  theme_void() +
  theme(legend.title = element_text(size = 6),
        legend.text = element_text(size = 5),
        legend.position = c(.8, .4))

```

```{r}
gg_point <- ggplot(bg_df, aes(x = county, y = percent_lowage_w,
                  color = county, tooltip = toolinfo, data_id = GEOID)) +
  geom_point_interactive(size=7, alpha = 0.2, color = "steelblue4") +
  scale_y_continuous(limits = c(0, 100),
                     labels = scales::percent_format(scale = 1),
                     name = "Percent of Population") +
  scale_x_discrete(name = "",
                   labels = function(groups) str_wrap(groups, width = 10)) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.text = element_text(size = 12),
        axis.text.x = element_text(size = 11),
        strip.background = element_rect(color = "black", fill = "#f1f1f1"),
        strip.text.x = element_text(size = 12),
        strip.placement = "outside")

# girafe(ggobj = gg_point)

gg_point_flip <- ggplot(bg_df, aes(x = percent_lowage_w, y = fct_rev(county),
                              color = percent_lowage_w, tooltip = toolinfo, 
                              data_id = GEOID)) +
  geom_point_interactive(size = 7, alpha = 0.2, color = "darkgreen") +
  scale_x_continuous(limits = c(0, 100),
                     labels = scales::percent_format(scale = 1),
                     name = "Percent of Population") +
  scale_y_discrete(name = "",
                   labels = function(groups) str_wrap(groups, width = 10)) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.text = element_text(size = 12),
        axis.text.x = element_text(size = 11),
        strip.background = element_rect(color = "black", fill = "#f1f1f1"),
        strip.text.x = element_text(size = 12),
        strip.placement = "outside")

```

### Workers in Jobs Paying Less Than $15,000/year, by Where They Work
```{r}
girafe(ggobj = gg_point + gg_map + plot_layout(widths = c(0.45, 0.65)), 
       width_svg = 12, height_svg = 6) %>%
  girafe_options(opts_hover(css = "fill:darkorange;stroke:darkgreen;stroke-width:2px;"))
```

### Workers in Jobs Paying Less Than $15,000/year, by Where They Work (Alternative)
```{r}
girafe(ggobj = gg_point_flip + gg_map + plot_layout(widths = c(0.45, 0.65)), 
       width_svg = 12, height_svg = 6) %>%
  girafe_options(opts_hover(css = "fill:darkorange;stroke:darkgreen;stroke-width:2px;"))
```

